#!/bin/sh
### BEGIN INIT INFO
# Provides:          rectoverso
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:      Start & stop rectoverso node server
### END INIT INFO

APP=rectoverso
SCRIPT="/usr/bin/node"
ARGS="/home/erasme/projets/rectoverso/index.js"
RUNAS="erasme"

PIDFILE=/var/run/${APP}/rectoverso.pid
LOGFILE=/var/log/${APP}/rectoverso.log

# Creates PID dir (this dir is in tmps, so it needs to be created at every boot)
if [ ! -e /var/run//${APP} ]; then
  mkdir -p /var/run//${APP}
  chown erasme /var/run//${APP}
fi

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT $ARGS &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  # ps x | grep "$ARGS" | grep -v grep | while read pid ignore
  # do
  #   echo $pid > $PIDFILE
  # done;
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
